### ISSUE TITLE
Mohan: Assignment

### ISSUE THREAD

**Issue by kishore564** [kishore564/internship2020#10]
Create a file
**MOHAN_ASSIGNMENT.md**

Update answers for all below questions
[Questions](https://drive.google.com/open?id=16mFwFcpnkExhPi3K52Qg-q3NnST3hnesq3QrTwbhTec)

Use [MarkDown Cheat Sheet](https://www.markdownguide.org/cheat-sheet/)

**Comment by nagulapali** [comment]
done
